apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: elastic-gpu-telemetry/api-gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: GATEWAY_QUESTDB_PG_ADDR
              value: "questdb:8812"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
