replicaCount: 1

mq:
  image: telemetry-mq:latest
  service:
    port: 8080

questdb:
  image: questdb/questdb:7.3.3

streamer:
  image: telemetry-streamer:latest

collector:
  image: telemetry-collector:latest

apiGateway:
  image: telemetry-api-gateway:latest
  service:
    port: 8080
