{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "elastic-gpu-telemetry.fullname" . }}-api-gateway
  labels:
    {{- include "elastic-gpu-telemetry.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-gateway
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "elastic-gpu-telemetry.fullname" $ }}-api-gateway
                port:
                  name: http
          {{- end }}
    {{- end }}
{{- end }}
